### ISSUE TITLE
Not able to train the model

### ISSUE THREAD

**Issue by nkhlken** [shubham3121/DL-3#1]
Hi 

I get an error that reads "_ValueError: Error when checking target: expected dense_1 to have shape (85,) but got array with shape (86,)_", when I run "_model.fit(Xtrain, ytrain, validation_data = (Xvalid, yvalid), epochs = 3, batch_size = 20, callbacks = [checkpointer], verbose = 1)_" - basically while training the model.

Can you suggest what must I do please?

Thanks!
Netra

Screenshot:

![image](https://user-images.githubusercontent.com/38154455/41813003-b89c0270-774a-11e8-9e64-5124cf41894e.png)

**Comment by nkhlken** [comment]
Never mind  I fixed it.

**Comment by shubham3121** [comment]
@nkhlken Glad you fixed it, on your own. 👍
